### ISSUE TITLE
Multi Class ?

### ISSUE THREAD

**Issue by lolz0r** [auduno/deepdraw#1]
Hi,
Very cool work! I wonder how feasible it is to generate images with multiple classes together? For instance, "monkey bird dog" or "person car cat"

Imagine the insanity!

**Comment by auduno** [comment]
I've actually done some experiments with generating multiple classes together, see [this blogpost](http://auduno.com/post/125837418083/drawing-with-googlenet). I've been meaning to put the code for the examples out here, will try to do so in the next days. :)

**Comment by lolz0r** [comment]
Nice post! I long for the day when a AI assisted painting tool exists that allows toy to paint novel scenes in the style of Picasso or Van Gough; I have a feeling we are close! I look forward to checking out the ipython notebooks!

**Comment by auduno** [comment]
I put out the code for generating multiple classes together now. Enjoy!
